/*
 * ColourPanel.java
 *
 * Created on 28 February 2007, 09:20
 */

package fractal.gui.panel;

import fractal.gui.frames.ColorRangeJDialog;
import fractal.gui.util.UpdatableListModel;
import fractal.producer.Fractal;
import fractal.producer.colour.Colouring;
import fractal.producer.colour.ColouringStore;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Owner
 */
public class ColourPanel extends javax.swing.JPanel {
    private UpdatableListModel availableColouringModel = new UpdatableListModel()  {
        public int getSize() { return ColouringStore.getSize(); }
        public Object getElementAt(int index) { return ColouringStore.getColouring(index); }
    };
    private final UpdatableListModel fractalColouringModel = new UpdatableListModel()  {
        public int getSize() { return fractal==null?0:fractal.getColouringsSize(); }
        public Object getElementAt(int index) { return fractal.getColouring(index); }
    };
    
    
    Fractal fractal = null;
    ColorRangeJDialog crjd = null;
//    PropertyEditorJPanel 
//            propertyEditorJPanel1 = 
//            new PropertyEditorJPanel();
    
    /** Creates new form ColourPanel */
    public ColourPanel() {
        initComponents();
        jlAllColourings.setModel(availableColouringModel);
        jlFractalColourings.setModel(fractalColouringModel);
    }
    public void setFractal(Fractal f) {
        this.fractal=f;
        availableColouringModel.fireUpdate();
        fractalColouringModel.fireUpdate();
        fractalColouringsValueChanged(null);
        if(crjd!=null){
                crjd.setVisible(true);
                crjd.dispose();
                crjd=null;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAllColourings = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlFractalColourings = new javax.swing.JList();
        jbAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        propertyEditorJPanel1 = new fractal.gui.panel.util.PropertyEditorJPanel();
        jbColourDialog = new javax.swing.JButton();
        jbDel = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("Available Colourings ")));
        jlAllColourings.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlAllColourings);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("Fractal Colourings")));
        jlFractalColourings.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlFractalColourings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fractalColouringsValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(jlFractalColourings);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jbAdd.setText(new String("Add"));
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("Colouring Properties")));
        jbSave.setText(new String("Save"));
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbCancel.setText(new String("Cancel"));
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(propertyEditorJPanel1);

        jbColourDialog.setText(new String("Edit Colour Map 1"));
        jbColourDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbColourDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addComponent(jbColourDialog))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbColourDialog)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jbDel.setText(new String("Del"));
        jbDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jbAdd)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDel)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbDel)
                            .addComponent(jbAdd))
                        .addGap(179, 179, 179)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        Colouring c = (Colouring)jlFractalColourings.getSelectedValue();
        if( c == null ) return;
        propertyEditorJPanel1.load(c);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        Colouring c = (Colouring)jlFractalColourings.getSelectedValue();
        if( c == null ) return;
        propertyEditorJPanel1.save(c);
    }//GEN-LAST:event_jbSaveActionPerformed
    
    private void fractalColouringsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fractalColouringsValueChanged
        Colouring c = (Colouring)jlFractalColourings.getSelectedValue();
        System.out.println("Colouring Changed:"+c);
        if( c == null ) {
            propertyEditorJPanel1.setBean(null);
            propertyEditorJPanel1.revalidate();
            propertyEditorJPanel1.repaint();
            return;
        }
        propertyEditorJPanel1.setBean(c);
        propertyEditorJPanel1.load(c);
        propertyEditorJPanel1.revalidate();
        propertyEditorJPanel1.repaint();
    }//GEN-LAST:event_fractalColouringsValueChanged
    
    private void jbDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDelActionPerformed
        Colouring c = (Colouring)jlFractalColourings.getSelectedValue();
        if( c == null ) return;
        fractal.removeColouring(c);
        if(jlFractalColourings.getMaxSelectionIndex()!=0)jlFractalColourings.setSelectedIndex(0);
        fractalColouringsValueChanged(null);
        fractalColouringModel.fireUpdate();
    }//GEN-LAST:event_jbDelActionPerformed
    
    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        Colouring c = (Colouring)jlAllColourings.getSelectedValue();
        if( c == null) return;
        fractal.addColouring(c.clone());
        fractalColouringModel.fireUpdate();
    }//GEN-LAST:event_jbAddActionPerformed
    
    private void jbColourDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbColourDialogActionPerformed
        if( crjd == null ){
            crjd = new ColorRangeJDialog((JFrame)SwingUtilities.getRoot(this),fractal);
        }
        crjd.setVisible(true);
    }//GEN-LAST:event_jbColourDialogActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbColourDialog;
    private javax.swing.JButton jbDel;
    private javax.swing.JButton jbSave;
    private javax.swing.JList jlAllColourings;
    private javax.swing.JList jlFractalColourings;
    private fractal.gui.panel.util.PropertyEditorJPanel propertyEditorJPanel1;
    // End of variables declaration//GEN-END:variables
    
}
