/*
 * FormulaJpanel.java
 *
 * Created on 25 February 2007, 21:17
 */

package fractal.gui.panel;

import fractal.gui.util.UpdatableListModel;
import fractal.producer.Fractal;
import fractal.producer.formula.Formula;
import fractal.producer.formula.FormulaStore;
import fractal.producer.formula.MergeFormula;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/**
 *
 * @author  Owner
 */
public class FormulaJPanel extends javax.swing.JPanel {
    private UpdatableListModel availableFormulasModel = new UpdatableListModel()  {
        public int getSize() { return FormulaStore.getSize(); }
        public Object getElementAt(int index) { return FormulaStore.getFormulas().get(index); }
    };
    private final UpdatableListModel fractalFormulasModel = new UpdatableListModel()  {
        public int getSize() { return fractal==null?0:fractal.getFormulaArray().size(); }
        public Object getElementAt(int index) { return fractal.getFormulaArray().get(index); }
    };
    
    Fractal fractal = null;
    /** Creates new form FormulaJpanel */
    public FormulaJPanel() {
        initComponents();
        jlAllFormulas.setModel(availableFormulasModel);
        jlFractalFormulas.setModel(fractalFormulasModel);
    }
    public void setFractal(Fractal f) {
        this.fractal=f;
        fractalFormulaChanged(null);
        fractalFormulasModel.fireUpdate();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAllFormulas = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        propertyEditor = new fractal.gui.panel.util.PropertyEditorJPanel();
        jbLoadBean = new javax.swing.JButton();
        jbSaveBean = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlFractalFormulas = new javax.swing.JList();
        jbAddFormula = new javax.swing.JButton();
        jbDelFormula = new javax.swing.JButton();
        jbSetFirstFormula = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfMaxIteration = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtfForceNLoops = new javax.swing.JTextField();
        jbForceLoops = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("All Formulas")));
        jlAllFormulas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlAllFormulas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("Current Formula")));

        jbLoadBean.setText(new String("Save"));
        jbLoadBean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadBeanActionPerformed(evt);
            }
        });

        jbSaveBean.setText(new String("Cancel"));
        jbSaveBean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveBeanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertyEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbLoadBean)
                        .addGap(17, 17, 17)
                        .addComponent(jbSaveBean)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(propertyEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLoadBean)
                    .addComponent(jbSaveBean))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new String("Fractal Formulas")));
        jlFractalFormulas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlFractalFormulas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fractalFormulaChanged(evt);
            }
        });

        jScrollPane2.setViewportView(jlFractalFormulas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        jbAddFormula.setText(new String("Add->"));
        jbAddFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddFormulaActionPerformed(evt);
            }
        });

        jbDelFormula.setText(new String("<-Delete"));
        jbDelFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDelFormulaActionPerformed(evt);
            }
        });

        jbSetFirstFormula.setText(new String("Set First Formula->"));
        jbSetFirstFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetFirstFormulaActionPerformed(evt);
            }
        });

        jLabel1.setText(new String("First Formula Iterations"));

        jtfMaxIteration.setText(new String("125"));

        jButton1.setText(new String("Update"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfForceNLoops.setText(new String("0"));

        jbForceLoops.setText(new String("Update"));
        jbForceLoops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbForceLoopsActionPerformed(evt);
            }
        });

        jLabel2.setText(new String("Force N Loops"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAddFormula)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSetFirstFormula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfForceNLoops, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfMaxIteration, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jbForceLoops))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbDelFormula)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbDelFormula)
                            .addComponent(jbSetFirstFormula)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMaxIteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddFormula)
                    .addComponent(jtfForceNLoops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbForceLoops))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbForceLoopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbForceLoopsActionPerformed
      try{
        fractal.setForceLoops(Integer.parseInt(jtfForceNLoops.getText()));
      }catch(NumberFormatException nfe) {
          jtfForceNLoops.setText(Integer.toString(fractal.getForceLoops()));
      }
    }//GEN-LAST:event_jbForceLoopsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
        fractal.setMaxIteration(Integer.parseInt(jtfMaxIteration.getText()));
              }catch(NumberFormatException nfe) {
          jtfMaxIteration.setText(Integer.toString(fractal.getMaxIteration()));
      }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jbDelFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDelFormulaActionPerformed
        Object o = jlFractalFormulas.getSelectedValue();
        if( o == null ) return;
        if( jlFractalFormulas.getSelectedIndex() == 0 ) {
            JOptionPane.showMessageDialog(this,"Please Use 'set first formula to change first formula","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if( o instanceof MergeFormula ) {
            int indx = jlFractalFormulas.getSelectedIndex();
            fractal.getFormulaArray().remove(indx);// Merge Formula
            fractal.getFormulaArray().remove(indx);// Formula
        }
        if( o instanceof Formula ) {
            int indx = jlFractalFormulas.getSelectedIndex();
            fractal.getFormulaArray().remove(indx-1);// Merge Formula
            fractal.getFormulaArray().remove(indx-1);// Formula
        }
        jlFractalFormulas.clearSelection();
        fractalFormulaChanged(null);
    }//GEN-LAST:event_jbDelFormulaActionPerformed
    
    private void jbSetFirstFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetFirstFormulaActionPerformed
        Formula formula = (Formula)jlAllFormulas.getSelectedValue();
        if( formula == null ) return;
        if( fractalFormulasModel.getSize() == 0 ){
            fractal.getFormulaArray().add(formula.clone());
        }
        if( fractalFormulasModel.getSize() > 0 ) {
            fractal.getFormulaArray().set(0,formula.clone());
        }
        fractalFormulasModel.fireUpdate();
        fractalFormulaChanged(null);
    }//GEN-LAST:event_jbSetFirstFormulaActionPerformed
    
    private void jbSaveBeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveBeanActionPerformed
        int indx = jlFractalFormulas.getSelectedIndex();
        if( indx == -1 ) {
            this.propertyEditor.setBean(null);
            return;
        }
        Object o = jlFractalFormulas.getSelectedValue();
        this.propertyEditor.load(o);
    }//GEN-LAST:event_jbSaveBeanActionPerformed
    
    private void jbLoadBeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadBeanActionPerformed
        int indx = jlFractalFormulas.getSelectedIndex();
        if( indx == -1 ) {
            this.propertyEditor.setBean(null);
            return;
        }
        Object o = jlFractalFormulas.getSelectedValue();
        this.propertyEditor.save(o);
    }//GEN-LAST:event_jbLoadBeanActionPerformed
    
    private void fractalFormulaChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fractalFormulaChanged
        int indx = jlFractalFormulas.getSelectedIndex();
        if( indx == -1 ) {
            this.propertyEditor.setBean(null);
            return;
        }
        Object o = jlFractalFormulas.getSelectedValue();
        this.propertyEditor.setBean(o);
        propertyEditor.invalidate();
        propertyEditor.validate();
        propertyEditor.repaint();
    }//GEN-LAST:event_fractalFormulaChanged
    
    private void jbAddFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddFormulaActionPerformed
        Formula formula = (Formula)jlAllFormulas.getSelectedValue();
        if( formula == null ) return;
        if( fractalFormulasModel.getSize() == 0 ){
            fractal.getFormulaArray().add(formula.clone());
        }
        if( fractalFormulasModel.getSize() > 0 ) {
            fractal.getFormulaArray().add(new MergeFormula());
            fractal.getFormulaArray().add(formula.clone());
        }
        fractalFormulasModel.fireUpdate();
        fractalFormulaChanged(null);
    }//GEN-LAST:event_jbAddFormulaActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAddFormula;
    private javax.swing.JButton jbDelFormula;
    private javax.swing.JButton jbForceLoops;
    private javax.swing.JButton jbLoadBean;
    private javax.swing.JButton jbSaveBean;
    private javax.swing.JButton jbSetFirstFormula;
    private javax.swing.JList jlAllFormulas;
    private javax.swing.JList jlFractalFormulas;
    private javax.swing.JTextField jtfForceNLoops;
    private javax.swing.JTextField jtfMaxIteration;
    private fractal.gui.panel.util.PropertyEditorJPanel propertyEditor;
    // End of variables declaration//GEN-END:variables
    
}
