/*
 * SelectPointJDialog.java
 *
 * Created on 4 March 2007, 09:04
 */

package fractal.gui.panel.util;

import fractal.producer.Coordinates;
import fractal.producer.Fractal;
import fractal.producer.calc.ComplexNumber;
import fractal.producer.exception.RenderException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Owner
 */
public class SelectPointJDialog extends javax.swing.JDialog {
    
    /** Creates new form SelectPointJDialog */
    Fractal fractal;
    JPanel panel = new JPanel() {
        public void paint(Graphics g) {
            super.paint(g);
            try{
                BufferedImage image = fractal.getImage();
                if( image != null ) g.drawImage(image,0,0,null);
            }catch(RenderException re) {
                re.printStackTrace();
            }
        }
        public int getWidth() { return fractal.getWidth(); }
        public int getHeight() { return fractal.getHeight(); }
        public Dimension getSize() { return new Dimension(getWidth(),getHeight()); }
        public Dimension getPreferredSize() { return getSize(); }
    };
    
    ComplexNumber number = null;
    
    public SelectPointJDialog(JFrame frame, final Fractal fractal) {
        super(frame,true);
        initComponents();
        this.fractal=fractal;
        jScrollPane1.getViewport().setView(panel);
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Coordinates co = fractal.getCoordinates();
                Number r = co.getXValue(evt.getX(),fractal.getWidth());
                Number i = co.getYValue(evt.getY(),fractal.getHeight());
                number = fractal.getPrecisionContext().getComplexNumberFactory().createComplexNumber(r,i);
                setVisible(false);
            }
        });
        panel.addMouseMotionListener(new java.awt.event.MouseAdapter(){
            public void mouseMoved(MouseEvent evt) {
                Coordinates co = fractal.getCoordinates();
                Number r = co.getXValue(evt.getX(),fractal.getWidth());
                Number i = co.getYValue(evt.getY(),fractal.getHeight());
                number = fractal.getPrecisionContext().getComplexNumberFactory().createComplexNumber(r,i);
                jtReal.setText(r.toString());
                jtImag.setText(i.toString());
            }
        });
        panel.setSize(new Dimension(fractal.getWidth(),fractal.getHeight()));
        SwingUtilities.updateComponentTreeUI(this);
        setVisible(true);
        
   }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jbCancel = new javax.swing.JButton();
        jtReal = new javax.swing.JTextField();
        jtImag = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Real");

        jLabel2.setText("Imag");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCancel)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtReal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtImag, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtImag, jtReal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jLabel1)
                    .addComponent(jtReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtImag, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        number = null;
    }//GEN-LAST:event_jbCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPointJDialog(new JFrame(),new Fractal()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JTextField jtImag;
    private javax.swing.JTextField jtReal;
    // End of variables declaration//GEN-END:variables
    public ComplexNumber getComplexNumber() { return number; }
}
